# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'principal.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(898, 627)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("background-color: rgb(77, 213, 208);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 73, 16))
        self.label_2.setObjectName("label_2")
        self.agregar = QtWidgets.QPushButton(self.frame)
        self.agregar.setGeometry(QtCore.QRect(520, 70, 181, 81))
        self.agregar.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 22pt \"Nirmala UI\";")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("sources/Icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.agregar.setIcon(icon)
        self.agregar.setIconSize(QtCore.QSize(60, 60))
        self.agregar.setObjectName("agregar")
        self.graficar = QtWidgets.QPushButton(self.frame)
        self.graficar.setGeometry(QtCore.QRect(710, 70, 181, 81))
        self.graficar.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 22pt \"Nirmala UI\";")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("sources/graf.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.graficar.setIcon(icon1)
        self.graficar.setIconSize(QtCore.QSize(60, 60))
        self.graficar.setObjectName("graficar")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(20, 210, 861, 401))
        self.frame_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:20px;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setStyleSheet("Qframe{\n"
"border:none;\n"
"}")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.viscograf = QtWidgets.QVBoxLayout()
        self.viscograf.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.viscograf.setContentsMargins(9, 9, 9, 9)
        self.viscograf.setSpacing(6)
        self.viscograf.setObjectName("viscograf")
        self.verticalLayout_3.addLayout(self.viscograf)
        self.verticalLayout_3.setStretch(0, 1)
        self.verticalLayout_3.setStretch(1, 5)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Viscosimetro"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Viscosimetro</span></p></body></html>"))
        self.agregar.setText(_translate("MainWindow", "Agregar"))
        self.graficar.setText(_translate("MainWindow", "Graficar"))
        self.label.setText(_translate("MainWindow", "Viscosidad vs temperatura"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
