# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'principal.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(958, 691)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("background-color: rgb(77, 213, 208);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 73, 16))
        self.label_2.setObjectName("label_2")
        self.agregar = QtWidgets.QPushButton(self.frame)
        self.agregar.setGeometry(QtCore.QRect(510, 80, 201, 81))
        self.agregar.setStyleSheet("background-color: rgb(184, 238, 236);\n"
"font: 22pt \"Nirmala UI\";\n"
"color: #444444;\n"
"font-weight: bold;\n"
"border-radius:20px;\n"
"\n"
"")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("sources/add-document.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.agregar.setIcon(icon)
        self.agregar.setIconSize(QtCore.QSize(60, 60))
        self.agregar.setObjectName("agregar")
        self.graficar = QtWidgets.QPushButton(self.frame)
        self.graficar.setGeometry(QtCore.QRect(730, 80, 201, 81))
        self.graficar.setStyleSheet("background-color: rgb(184, 238, 236);\n"
"font: 22pt \"Nirmala UI\";\n"
"color: #444444;\n"
"font-weight: bold;\n"
"border-radius:20px;")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("sources/chart-histogram.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.graficar.setIcon(icon1)
        self.graficar.setIconSize(QtCore.QSize(60, 60))
        self.graficar.setObjectName("graficar")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(10, 230, 681, 451))
        self.frame_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:20px;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setStyleSheet("Qframe{\n"
"border:none;\n"
"}")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.viscograf = QtWidgets.QVBoxLayout()
        self.viscograf.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.viscograf.setContentsMargins(9, 9, 9, 9)
        self.viscograf.setSpacing(6)
        self.viscograf.setObjectName("viscograf")
        self.verticalLayout_3.addLayout(self.viscograf)
        self.verticalLayout_3.setStretch(1, 5)
        self.tabla_datos = QtWidgets.QTableWidget(self.frame)
        self.tabla_datos.setGeometry(QtCore.QRect(730, 230, 191, 451))
        self.tabla_datos.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:20px;")
        self.tabla_datos.setObjectName("tabla_datos")
        self.tabla_datos.setColumnCount(0)
        self.tabla_datos.setRowCount(0)
        self.tabla_recientes = QtWidgets.QTableWidget(self.frame)
        self.tabla_recientes.setGeometry(QtCore.QRect(20, 30, 481, 181))
        self.tabla_recientes.setMinimumSize(QtCore.QSize(481, 181))
        self.tabla_recientes.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:20px;")
        self.tabla_recientes.setAlternatingRowColors(True)
        self.tabla_recientes.setColumnCount(4)
        self.tabla_recientes.setObjectName("tabla_recientes")
        self.tabla_recientes.setRowCount(0)
        self.tabla_recientes.horizontalHeader().setCascadingSectionResizes(True)
        self.tabla_recientes.horizontalHeader().setDefaultSectionSize(39)
        self.tabla_recientes.horizontalHeader().setStretchLastSection(True)
        self.tabla_recientes.verticalHeader().setCascadingSectionResizes(True)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Viscosimetro"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Viscosimetro</span></p></body></html>"))
        self.agregar.setText(_translate("MainWindow", "Agregar"))
        self.graficar.setText(_translate("MainWindow", "Graficar"))
        self.label.setText(_translate("MainWindow", "Viscosidad vs temperatura"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
